/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=WorkerBindings src/worker-bindings.d.ts` (hash: d3b03c4e3467da49356836b354fd245a)
interface __BaseEnv_WorkerBindings {
	BUCKET: R2Bucket;
	DB: D1Database;
	AI: Ai;
	NOTIFY_ENABLED: string;
	NOTIFY_TIME_PARSER: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NOTIFY_ENABLED" | "NOTIFY_TIME_PARSER">> {}
}
